# Generated by Django 4.1.6 on 2023-03-15 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_orderitem_price_orderitem_product_orderitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items_order",
                to="store.order",
            ),
        ),
    ]
