# Generated by Django 4.1.6 on 2023-03-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_orderitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
