# Generated by Django 4.1.6 on 2023-03-16 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_order_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
    ]
