# Generated by Django 4.1.6 on 2023-03-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projectaccount", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
